---
title: "Outlier loci detection PCAdapt"
output: github_document
---

## PCAdapt between O. victoirae VS O. hexactis including O. victoriae from South Georgia
See tutorial at https://bcm-uga.github.io/pcadapt/articles/pcadapt.html

Generate input file in Terminal
```{bash, error=TRUE, results='hide'}
cd ./ophionotus/SNPfiltering/filtering1/9_thin140

vcftools --vcf vic_hex_thin140.vcf.recode.vcf --plink

mv vic_hex_thin140.ped vic_hex.ped
```

Run pcadapt in R
```{r, eval=F, echo=T}
library(pcadapt)

vic_hex_pcadapt <- read.pcadapt("./vic_hex.ped", type = "ped")

x <- pcadapt(input = vic_hex_pcadapt, K = 20) #assuming samples are diploid

#plot pcadapt 
plot(x, option = "screeplot") #K=4 is the optimal choice for K

#Plot PCA on axis 1 and 2
plot(x,option="scores",i=1,j=2)

#Plot PCA on axis 3 and 4
plot(x, option = "scores", i = 3, j = 4)

#Computing the test statistic based on PCA
x <- pcadapt(vic_hex_pcadapt, K = 4)
summary(x)

#Manhattan Plot
plot(x , option = "manhattan")

#QQ Plot
plot(x, option="qqplot", threshold=0.01)

#Histograms of the test statistic and of the p-values
hist(x$pvalues, xlab = "p-values", main = NULL, breaks = 50, col = "orange")

#histogram of the test statistic ð·ð‘—.
plot(x, option = "stat.distribution")

#choosing a cutoff for outlier detection - Benjamini-Hochberg Procedure
#chose a more conservative cutoff with alpha = 0.01 - see https://onlinelibrary.wiley.com/doi/10.1111/j.0030-1299.2005.13727.x

padj <- p.adjust(x$pvalues,method="BH")
alpha <- 0.01
outliers <- which(padj < alpha)
length(outliers) #27 outliers

loci <- read.table("./vic_hex_loci.txt", header=F)
outliers1 <- as.character(loci[,1])[outliers]
outliers1 #27 outliers

write.csv(outliers1, file="vic_hex_outliers.csv")
```

## PCAdapt within O. victoirae 

Generate input file in Terminal
```{bash, error=TRUE, results='hide'}
cd ./ophionotus/SNPfiltering/filtering2/9_thin140

vcftools --vcf vic_thin140.vcf.recode.vcf --plink

mv vic_thin140.ped vic.ped
```

Run pcadapt in R
```{r, eval=F, echo=T}
vic_pcadapt <- read.pcadapt("./vic.ped", type = "ped")

x <- pcadapt(input = vic_pcadapt, K = 20) #assuming sampels are diploid

#plot pcadapt 
plot(x, option = "screeplot") #K=3 is the optimal choice for K

#Plot PCA on axis 1 and 2
plot(x,option="scores",i=1,j=2)

#Plot PCA on axis 3 and 4
plot(x, option = "scores", i = 3, j = 4)

#Computing the test statistic based on PCA
x <- pcadapt(vic_pcadapt, K = 3)
summary(x)

#Manhattan Plot
plot(x , option = "manhattan")

#QQ Plot
plot(x, option="qqplot", threshold=0.01)

#Histograms of the test statistic and of the p-values
hist(x$pvalues, xlab = "p-values", main = NULL, breaks = 50, col = "orange")

#histogram of the test statistic ð·ð‘—.
plot(x, option = "stat.distribution")

#Benjamini-Hochberg Procedure with alpha = 0.01

padj <- p.adjust(x$pvalues,method="BH")
alpha <- 0.01
outliers <- which(padj < alpha)
length(outliers) #13 outliers

loci <- read.table("./vic_loci.txt", header=F)
outliers1 <- as.character(loci[,1])[outliers]
outliers1 #13 outliers

write.csv(outliers1, file="vic_outliers.csv")
```

## PCAdapt within O. hexactis

Generate input file in Terminal
```{bash, error=TRUE, results='hide'}
cd ./ophionotus/SNPfiltering/filtering3/9_thin140

vcftools --vcf hex_thin140.vcf.recode.vcf --plink

mv hex_thin140.ped hex.ped
```

Run pcadapt in R
```{r, eval=F, echo=T}
hex_pcadapt <- read.pcadapt("./hex.ped", type = "ped")

x <- pcadapt(input = hex_pcadapt, K = 20) #assuming sampels are diploid

#plot pcadapt 
plot(x, option = "screeplot") #K=2 is the optimal choice for K

#Plot PCA on axis 1 and 2
plot(x,option="scores",i=1,j=2)

#Plot PCA on axis 3 and 4
plot(x, option = "scores", i = 3, j = 4)

#Computing the test statistic based on PCA
x <- pcadapt(vic_pcadapt, K = 2)
summary(x)

#Manhattan Plot
plot(x , option = "manhattan")

#QQ Plot
plot(x, option="qqplot", threshold=0.01)

#Histograms of the test statistic and of the p-values
hist(x$pvalues, xlab = "p-values", main = NULL, breaks = 50, col = "orange")

#histogram of the test statistic ð·ð‘—.
plot(x, option = "stat.distribution")

#Benjamini-Hochberg Procedure with alpha = 0.01

padj <- p.adjust(x$pvalues,method="BH")
alpha <- 0.01
outliers <- which(padj < alpha)
length(outliers) #3 outliers

loci <- read.table("./hex_loci.txt", header=F)
outliers1 <- as.character(loci[,1])[outliers]
outliers1 #3 outliers

write.csv(outliers1, file="hex_outliers.csv")
```